use_frameworks!

platform :ios, '9.0'

target 'TableViewController_Example' do
  pod 'TableViewController', :path => '../'

  target 'TableViewController_Tests' do
    inherit! :search_paths

    
  end
end
